// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Mx-_IbRv4FXwe-ZKxG8MTDzFwa57QE0',
    appId: '1:621042869280:web:5e655f8041b72714c60845',
    messagingSenderId: '621042869280',
    projectId: 'budget-bites-9d245',
    authDomain: 'budget-bites-9d245.firebaseapp.com',
    databaseURL: 'https://budget-bites-9d245-default-rtdb.firebaseio.com',
    storageBucket: 'budget-bites-9d245.appspot.com',
    measurementId: 'G-397ZM618D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBs2-xlyxOf_ZlBylnW7eyPa-Cv32hLE',
    appId: '1:621042869280:android:c35c77ea84e22ea8c60845',
    messagingSenderId: '621042869280',
    projectId: 'budget-bites-9d245',
    databaseURL: 'https://budget-bites-9d245-default-rtdb.firebaseio.com',
    storageBucket: 'budget-bites-9d245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4SIQJlbMLeZAGUIkdjrTKudsX3ezxU3g',
    appId: '1:621042869280:ios:b9fa0361cef08805c60845',
    messagingSenderId: '621042869280',
    projectId: 'budget-bites-9d245',
    databaseURL: 'https://budget-bites-9d245-default-rtdb.firebaseio.com',
    storageBucket: 'budget-bites-9d245.appspot.com',
    iosBundleId: 'com.sahilak.bb',
  );

}